version: "3.5"
services:
  background_dev:
    build:
      context: .
      dockerfile: Dockerfile-background-executor
    volumes:
      - .:/app
    depends_on:
      - redis_dev
    restart: always
    environment:
      - TZ=Europe/Moscow

  redis_dev:
    image: redis
    restart: always
    environment:
      - TZ=Europe/Moscow
    # ports:
    #   - "6377:6379"

  flask_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis_dev
    restart: always
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Moscow

#  celery_dev:
#    build:
#      context: .
#      dockerfile: Dockerfile-celery
#    depends_on:
#      - redis_dev
#    restart: always
#    volumes:
#      - .:/app
#    entrypoint: celery
#    command: -A gpsdev_flask.celery_app.app_celery worker --loglevel=info
#    environment:
#      - TZ=Europe/Moscow
#  celery-beat:
#    build:
#      context: .
#      dockerfile: Dockerfile-celery
#    depends_on:
#      - redis
#    restart: always
#    volumes:
#      - .:/app
#    entrypoint: celery
#    command: -A gpsdev_flask.celery_app beat -l info
