version: "3.3"
services:
  background:
    build:
      context: .
      dockerfile: Dockerfile-background-executor
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
#    environment:
#      - ENV=production

  redis-executor:
    build:
      context: .
      dockerfile: Dockerfile-redis-executor
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
    ports:
      - "5000:5000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    depends_on:
      - redis
    restart: always
    volumes:
      - .:/app
    entrypoint: celery
    command: -A gpsdev_flask.celery_app.app_celery worker --loglevel=info

