version: "3.3"
services:
  background:
    build:
      context: .
      dockerfile: Dockerfile-background-executor
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
#    environment:
#      - ENV=production

  redis:
    image: redis
    restart: always

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
    ports:
      - "5000:5000"

