version: "3.3"
services:
  background:
    build:
      context: .
      dockerfile: Dockerfile-background-executor
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    restart: always
    ports:
      - "6378:6379"

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
    ports:
      - "5001:5000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    depends_on:
      - redis
    restart: always
    volumes:
      - .:/app
    entrypoint: celery
    command: -A gpsdev_flask.celery_app.app_celery worker --loglevel=info
#  celery-beat:
#    build:
#      context: .
#      dockerfile: Dockerfile-celery
#    depends_on:
#      - redis
#    restart: always
#    volumes:
#      - .:/app
#    entrypoint: celery
#    command: -A gpsdev_flask.celery_app beat -l info

