version: "3.3"
services:
  background:
    build:
      context: .
      dockerfile: Dockerfile-background-executor
    volumes:
      - .:/app
    depends_on:
      - redis
    network_mode: "host"
    restart: always
    environment:
      - ENV=production

  redis:
    image: redis
    network_mode: "host"
    restart: always
